export const FETCH_DATA_CITIES = "FETCH_DATA_CITIES";
export const FETCH_DATA_ITINERARIES = "FETCH_DATA_ITINERARIES";
export const FETCH_DATA_ITINERARIES_BY_ID_CITY ="FETCH_DATA_ITINERARIES_BY_ID_CITY";
export const FETCH_DATA_ACTIVITIES = "FETCH_DATA_ACTIVITIES";
export const FETCH_DATA_ACTIVITIES_BY_ID_ITINERARY = "FETCH_DATA_ACTIVITIES_BY_ID_ITINERARY";
export const FETCH_IMG_BY_USER_ID = "FETCH_IMG_BY_USER_ID";

export const LEAVE_DATA_CITY = "LEAVE_DATA_CITY";
export const LEAVE_DATA_USER = "LEAVE_DATA_USER";
export const LEAVE_DATA_ITINERARY = "LEAVE_DATA_ITINERARY";
export const LEAVE_DATA_COMMENT = "LEAVE_DATA_COMMENT";
export const LEAVE_DATA_LIKE = "LEAVE_DATA_LIKE";


export const SET_FILTER_TEXT = "SET_FILTER_TEXT";
export const SET_ON_FILTER_TEXT_CHANGE = "SET_ON_FILTER_TEXT_CHANGE";
export const SET_CITY_ID_SELECTED = "SET_CITY_ID_SELECTED";
export const SET_ITINERARY_ID_SELECTED = "SET_ITINERARY_ID_SELECTED";
export const SET_USER_LOGGED = "SET_USER_LOGGED";

export const GET_TOKEN = "GET_TOKEN";


export const ADD_ARTICLE = "ADD_ARTICLE";
export const ADD_ITINERARY = "ADD_ITINERARY";


export const urlImages = 'http://localhost:5000/';


